# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: microservicio.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'microservicio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13microservicio.proto\x12\rmicroservicio\"\x1f\n\rSaludoRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\"\x1e\n\x0bSaludoReply\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2V\n\rSaludoService\x12\x45\n\x07Saludar\x12\x1c.microservicio.SaludoRequest\x1a\x1a.microservicio.SaludoReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'microservicio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SALUDOREQUEST']._serialized_start=38
  _globals['_SALUDOREQUEST']._serialized_end=69
  _globals['_SALUDOREPLY']._serialized_start=71
  _globals['_SALUDOREPLY']._serialized_end=101
  _globals['_SALUDOSERVICE']._serialized_start=103
  _globals['_SALUDOSERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
